version: '3'

services:
  # db:
  #   image: postgres
  web:
    build: .
    command: sh -c "python3 manage.py makemigrations scraper &&
                    python manage.py sqlmigrate scraper 0001 &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - $PWD/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
